### PR TITLE
restyle upsert dialogs

### PR DESCRIPTION
**Pull request by zeroxjackson**
bruh... i was doing this 🙄 @isaiahnields

### CODE REVIEW

**Comment by isaiahnields** [comment]
oh shit my b

**Comment by isaiahnields** [comment]
what were the differences in our changes?

**Comment by zeroxjackson** [comment]
@isaiahnields i think this is a cleaner design

**Comment by isaiahnields** [comment]
merge conflicts weren't resolved properly

**Comment by isaiahnields** [comment]
did you have the task claimed? to make sure this doesn't happen again we can claim tasks.

**Comment by isaiahnields** [comment]
Screen Shot 2020-12-05 at 11 18 45 PM

**Comment by isaiahnields** [comment]
@jacksonet00 something to that effect happened on all the cards ^

**Comment by isaiahnields** [comment]
Also, pls be sure to set spacing={3} for the `<Grid container />` in order to get rid of the scrollbar.

**Comment by zeroxjackson** [comment]
@isaiahnields mine do not have a scroll bar, mine are clean. Also, yes I claimed this task it is assigned to me on github.

here are my cards:

Screen Shot 2020-12-05 at 11 29 12 PM
Screen Shot 2020-12-05 at 11 28 55 PM
Screen Shot 2020-12-05 at 11 28 41 PM
Screen Shot 2020-12-05 at 11 28 35 PM

**Pull request merged**
